### ISSUE TITLE
缺少文件Operator.DE

### ISSUE THREAD

**Issue by Wesley273** [HandingWangXDGroup/Two_Arch2-in-python#1]
Traceback (most recent call last):
  File "c:\Users\wesley\Downloads\Two_Arch2-in-python-main\main.py", line 1, in <module>
    from PyEA import PyEA
  File "c:\Users\wesley\Downloads\Two_Arch2-in-python-main\PyEA.py", line 5, in <module>
    from Algorithm.MOEADDRA.MOEADDRA import MOEADDRA
  File "c:\Users\wesley\Downloads\Two_Arch2-in-python-main\Algorithm\MOEADDRA\MOEADDRA.py", line 6, in <module>
    from Operator.DE import DEandMuation
ModuleNotFoundError: No module named 'Operator.DE'

**Comment by zssongzs** [comment]
Hi, this implementation is based on the following link:
https://github.com/COLA-Laboratory/A-python-package-to-MOEA
if you want to test other algorithms like MOEADDRA, you can find the DEoperator in that link.
Many thanks

**Comment by Wesley273** [comment]
Thanks a lot
发自我的 iPhone

在 2023年10月27日，09:41，zssongzs ***@***.***> 写道：

﻿

Hi, this implementation is based on the following link:
https://github.com/COLA-Laboratory/A-python-package-to-MOEA
if you want to test other algorithms like MOEADDRA, you can find the DEoperator in that link.
Many thanks
